export type TourStop = { id: string; title: string; board: string; group: string; explanation: string; example: string; question: string; choices: [string, string]; replies: [string, string] };
export const tourStops: TourStop[] = [
  {id:'overview',title:'Command Desk',board:'Overview',group:'Your day',explanation:"I'm Cixy. This is where your day comes together: appointments, follow-ups, property records and your pipeline. Your real workspace starts empty and grows with the records you save.",example:'One place for your next move.',question:'What would you like to focus on?',choices:['Follow-ups','My schedule'],replies:['I’ll help you keep the next conversation in sight.','We’ll keep appointments and tasks easy to find.']},
  {id:'inbox',title:'Inbox & Email',board:'Email',group:'Your day',explanation:'This box previews your connected Google inbox. The Email board holds saved drafts. Google must be configured and connected first; reading a message or saving a draft does not send anything.',example:'Sample message · A buyer asks about a showing.',question:'What would you do with this message?',choices:['Prepare a reply','Plan a showing'],replies:['A reviewed reply starts as a draft. Sending is not connected yet.','Save an appointment, then review it before publishing to Google.']},
  {id:'day',title:'My Day',board:'Calendar',group:'Your day',explanation:'My Day brings your upcoming appointments into view. Use it to decide what needs your attention next, then open Calendar for the wider picture.',example:'Sample day · 10:00 property visit · 14:00 client call',question:'How do you like to plan?',choices:['One day at a time','Look ahead'],replies:['Start here for a short, focused agenda.','The Calendar box gives you the wider view.']},
  {id:'calendar',title:'Calendar',board:'Calendar',group:'Your day',explanation:'Browse dates and save appointments with start and end times. Connected Google events can be read here. Publishing a saved appointment requires review; automatic conflict checking and attendee invitations are not available.',example:'Sample appointment · Property visit, Thursday at 10:00',question:'Would you connect a calendar?',choices:['Google Calendar','Keep it manual'],replies:['Connections is where you authorize your own Google account.','You can save appointments without connecting a provider.']},
  {id:'tasks',title:'Tasks',board:'Calendar',group:'Your day',explanation:'Tasks are the small steps that keep work moving. Add a due date and mark a task complete when you finish. A follow-up task is a reminder, not an automatically sent message.',example:'Sample task · Follow up after the property visit',question:'Try completing this sample task.',choices:['Mark complete','Leave it open'],replies:['Done! Your sample task is complete. Nothing was changed in a real workspace.','It stays on the sample to-do list until you are ready.']},
  {id:'leads',title:'Hot Property Leads & Leads',board:'Leads',group:'People & deals',explanation:'This box surfaces leads you have saved. The Leads board keeps contact details, notes and a pipeline stage together. It does not automatically find or purchase new leads.',example:'Sample lead · Taylor Morgan · New',question:'You have spoken with Taylor. What happens next?',choices:['Move to Contacted','Create a follow-up'],replies:['Taylor is now Contacted in this demo. Stages show where a conversation stands.','A sample follow-up is ready. In your workspace, the Follow up button saves a task.']},
  {id:'clients',title:'Clients',board:'Clients',group:'People & deals',explanation:'Clients is your contact book for ongoing relationships. Save names, email addresses, phone numbers and notes so you can prepare for the next conversation.',example:'Sample client · Taylor Morgan · Looking for a new home',question:'What would you record first?',choices:['Contact details','Conversation notes'],replies:['Keep the best way to reach your client in one place.','Notes help you pick up the conversation with context.']},
  {id:'properties',title:'Active Listings & Properties',board:'Properties',group:'People & deals',explanation:'This box previews your saved properties. The Properties board holds prices, bedrooms, bathrooms, status, notes and listing links. Illustrations are generic; links are bookmarks, not imported listings or verified comps.',example:'Sample property · Cedar House · $285,000',question:'How would you start a property record?',choices:['Enter the details','Save a listing link'],replies:['Add the facts you know, then update them as you learn more.','Save a public link for reference. Renoxis does not fetch the listing for you.']},
  {id:'transactions',title:'Transactions',board:'Transactions',group:'People & deals',explanation:'Track a deal’s status, price, expected commission, progress and next step. These are your entries, not verified closings. Team closings can record a pending platform fee; recording it does not collect payment.',example:'Sample deal · Cedar House · Offer · Review terms',question:'What should stay visible on a deal?',choices:['The next step','Expected commission'],replies:['A clear next step helps the deal keep moving.','Enter your estimate and keep it current as the deal changes.']},
  {id:'pipeline',title:'Lead Pipeline',board:'Leads',group:'People & deals',explanation:'The bottom pipeline strip counts leads at each stage: New, Contacted, Showing, Offer, Under contract and Closed. Select a stage to open the matching leads.',example:'Sample pipeline · New 1 → Contacted 0 → Showing 0',question:'Try a stage filter.',choices:['Show New leads','Show Contacted leads'],replies:['The demo filter shows the new lead awaiting a first conversation.','No sample leads are contacted yet. Empty stages are normal.']},
  {id:'forecast',title:'Commission Forecast',board:'Analytics',group:'People & deals',explanation:'This box adds the expected commissions you enter on transactions, excluding cancelled deals. It is a forecast, not cash, a payout or guaranteed income.',example:'Sample estimate · $6,000 expected commission',question:'How should we read this number?',choices:['An estimate','Show me the source'],replies:['Exactly. Keep forecasts separate from money actually received.','Open Transactions to review the entries behind the total.']},
  {id:'analytics',title:'Analytics',board:'Analytics',group:'People & deals',explanation:'Analytics summarizes expected commission, closed deals, properties, open tasks and pipeline stages. The numbers come from saved records, so accurate entries matter.',example:'Sample snapshot · 1 property · 1 open task · 0 closed deals',question:'Which number matters to you today?',choices:['Open tasks','Pipeline progress'],replies:['Start with the work you can act on today.','Review which conversations need to move to the next stage.']},
  {id:'cixy',title:'Cixy’s Office',board:'Overview',group:'Create with Cixy',explanation:'This is my place in your workspace. Talk to me for real-estate guidance and drafts using a limited snapshot of your records. Give a task saves a task for you; I do not independently execute it. Chat requires active access and an available AI provider.',example:'Try asking · Help me prepare for a property showing.',question:'What would you ask me for?',choices:['A follow-up draft','A showing checklist'],replies:['I can help shape the wording for you to review.','I can help organize questions and next steps using the facts you provide.']},
  {id:'renovation',title:'Renovation Studio',board:'Renovation Studio',group:'Create with Cixy',explanation:'The renovation tile opens a place to save project scope, budget, status and notes. Ask me to refine the brief. Photorealistic before-and-after generation is not connected.',example:'Sample brief · Kitchen refresh · $12,000 planning budget',question:'Where would you begin?',choices:['Define the scope','Plan the budget'],replies:['List the work you want done before comparing options.','Use a planning estimate, then verify costs with qualified providers.']},
  {id:'social',title:'Social Studio',board:'Social Studio',group:'Create with Cixy',explanation:'Organize captions and social drafts here. I can help with wording; you review and copy the finished draft to your platform. Renoxis does not publish posts automatically.',example:'Sample draft · A new chapter starts with the right home.',question:'What would you like to draft?',choices:['Property spotlight','Helpful local content'],replies:['Use accurate property details and review the final copy.','Start with facts you can verify and information your audience needs.']},
  {id:'documents',title:'Documents',board:'Documents',group:'Create with Cixy',explanation:'Keep private uploads and saved document links here. Download links are temporary. Cixy drafts can be saved as text files; that does not sign or send them.',example:'Sample document · Showing checklist.txt',question:'How would you organize your first document?',choices:['Upload a file','Save a link'],replies:['The real workspace supports PDF, PNG, JPG and text uploads within its size limit.','Use a public HTTPS link. The linked site controls access to its own file.']},
  {id:'studio',title:'Cixy Studio & appearance',board:'Cixy Studio',group:'Create with Cixy',explanation:'Customize my original artwork with skin, hair, eye and blazer tints, office palettes, and activity controls. Essentials are included. Premium collections are coming soon; appearance saves on this device.',example:'Original Cixy artwork · Smile, Wave, Sleep, Snack and Coffee',question:'Choose a pose for me.',choices:['Wave','Coffee'],replies:['Hello again! This is the same Cixy artwork used in your dashboard.','A little coffee break. Motion can be switched off, too.']},
  {id:'team',title:'Team',board:'Team',group:'Your workspace',explanation:'Create an office, invite members and work with owner, broker, agent and assistant roles. Access depends on role and record visibility. Private notes have their own sharing rules; owners and brokers have broader office oversight.',example:'Sample office · Owner · Broker · Agent · Assistant',question:'How will you work?',choices:['On my own','With a team'],replies:['Your personal workspace keeps the focus on your own book.','The Team board holds invitations, roles and office controls.']},
  {id:'wallet',title:'Ixis & office ledger',board:'Team',group:'Your workspace',explanation:'The Ixis box links to Apixis Wallet or your office ledger. Office email and offer drafts cost 50 and 100 Ixis; manually recording a property or contact is free. Buying Wallet credits does not automatically unlock premium outfits or credit the office ledger.',example:'Office actions · Contact 0 · Property record 0 · Email draft 50 · Offer draft 100 Ixis',question:'What should you check before a paid action?',choices:['The cost','Who pays'],replies:['Review the displayed cost before choosing the action.','Office actions use the office ledger; seat activation is a separate purchase.']},
  {id:'connections',title:'Connections & billing',board:'Connections',group:'Your workspace',explanation:'Connect supported services, review workspace preferences and manage access here. Renoxis currently has a $50 one-time activation plus a $50 monthly seat, paid with Ixis through Apixis Wallet. Setup and provider availability determine which connected tools work.',example:'Access · 5,000 Ixis activation + 5,000 Ixis per month',question:'What would you set up first?',choices:['My workspace preferences','Google connection'],replies:['Start with your display name, specialty and timezone.','Connect your own account after reviewing the requested access.']},
  {id:'search',title:'Search your workspace',board:'Overview',group:'Desk controls',explanation:'Search looks through the workspace records currently loaded and shows matching items. It is not a web search, MLS search or a search through uploaded file contents.',example:'Search the sample workspace',question:'Try searching these sample records.',choices:['Cedar','Taylor'],replies:['Found: Cedar House · Property record.','Found: Taylor Morgan · Lead record.']},
  {id:'add',title:'Add new',board:'Overview',group:'Desk controls',explanation:'Add new opens the form for the board you are viewing. On the overview it starts a task. Give each entry a clear name, fill in the relevant details and save.',example:'Sample task · Call Taylor after the showing',question:'Try adding the sample task.',choices:['Add sample task','Review first'],replies:['Sample task added! It exists only in this tour.','In the workspace, review the form before saving.']},
  {id:'refresh',title:'Workspace status, Refresh & Export',board:'Overview',group:'Desk controls',explanation:'The status line tells you when records are loading or need attention. Refresh reloads your saved data. Export downloads the loaded view; large workspaces are currently limited to the newest 1,000 records.',example:'Your private workspace · Refresh · Export',question:'What do you need?',choices:['Latest records','A copy of my data'],replies:['Use Refresh after changes elsewhere.','Use Export and check whether the view is truncated.']},
  {id:'navigation',title:'Navigation, account & themes',board:'Connections',group:'Desk controls',explanation:'The sidebar opens every board. The top shortcuts open the same destinations: My Day is Calendar, Pipeline is Leads and Marketing is Social Studio. Your account control opens Connections. Themes change the desk palette; the mobile menu keeps navigation within reach.',example:'Same workspace · Sidebar, shortcuts and mobile menu',question:'How would you move around?',choices:['Use the sidebar','Use quick shortcuts'],replies:['All 15 boards are available there.','Shortcuts take you to the most common destinations.']},
  {id:'faqs',title:'FAQs & help',board:'FAQs',group:'Your workspace',explanation:'FAQs explains privacy, connections, customization, installation and feature limits. You can replay this tour from there whenever you need a refresher. The installable web app still needs an internet connection.',example:'A little clarity, whenever you need it.',question:'Ready for your own workspace?',choices:['Let’s get started','I want to explore more'],replies:['Your real workspace will start with your own records.','Choose any box in the tour index to revisit it.']},
];
export function orderedTour(focus: string) {
  const priority = focus === 'Properties' ? ['properties','renovation','transactions'] : focus === 'Calendar' ? ['day','calendar','tasks'] : ['leads','clients','pipeline'];
  const ids = ['overview', ...priority];
  return [...ids.map(id => tourStops.find(s => s.id === id)!), ...tourStops.filter(s => !ids.includes(s.id))];
}
export function dashboardDestination(params: Record<string, string | string[] | undefined>) {
  const query = new URLSearchParams();
  for (const key of ['board','billing','invite','connection']) {
    const value = params[key];
    if (typeof value === 'string') query.set(key, value);
  }
  return '/dashboard' + (query.size ? '?' + query.toString() : '');
}
